version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
  web:
    build: .
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    depends_on:
      - db
  celery:
    build: .
    command: celery -A notification_service worker -l INFO
    depends_on:
      - web
  celery-beat:
    build: .
    command: celery -A notification_service beat -l INFO
    depends_on:
      - celery