# Generated by Django 4.1.3 on 2022-11-30 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Неправильный формат. Пример: 7XXXXXXXXXX (X - цифра от 0 до 9)', regex='^7[\\d]{10}$')], verbose_name='номер телефона')),
                ('phone_number_code', models.CharField(max_length=4, verbose_name='код мобильного оператора')),
                ('tag', models.CharField(max_length=128, verbose_name='тег')),
                ('timezone', models.CharField(max_length=30, verbose_name='часовой пояс')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(verbose_name='время запуска рассылки')),
                ('text', models.TextField(verbose_name='Текст')),
                ('properties', models.CharField(max_length=128, verbose_name='фильтр свойств клиентов')),
                ('date_end', models.DateTimeField(verbose_name='время окончания рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(verbose_name='время создания')),
                ('status', models.BooleanField(verbose_name='статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='клиент')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mail', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
