# Generated by Django 4.1.3 on 2022-11-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mailing',
            new_name='mail',
        ),
        migrations.AlterField(
            model_name='message',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
    ]
