# Generated by Django 4.1.3 on 2022-11-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_mailing_message_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.mail', verbose_name='рассылка'),
        ),
    ]
